// @ts-nocheck


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async modelsDir() : Promise<string> {
    return await TAURI_INVOKE("plugin:local-stt|models_dir");
},
async listGgmlBackends() : Promise<GgmlBackend[]> {
    return await TAURI_INVOKE("plugin:local-stt|list_ggml_backends");
},
async isModelDownloaded(model: SupportedSttModel) : Promise<boolean> {
    return await TAURI_INVOKE("plugin:local-stt|is_model_downloaded", { model });
},
async isModelDownloading(model: SupportedSttModel) : Promise<boolean> {
    return await TAURI_INVOKE("plugin:local-stt|is_model_downloading", { model });
},
async downloadModel(model: SupportedSttModel, channel: TAURI_CHANNEL<number>) : Promise<null> {
    return await TAURI_INVOKE("plugin:local-stt|download_model", { model, channel });
},
async getLocalModel() : Promise<SupportedSttModel> {
    return await TAURI_INVOKE("plugin:local-stt|get_local_model");
},
async setLocalModel(model: SupportedSttModel) : Promise<null> {
    return await TAURI_INVOKE("plugin:local-stt|set_local_model", { model });
},
async getServers() : Promise<Partial<{ [key in ServerType]: ServerHealth }>> {
    return await TAURI_INVOKE("plugin:local-stt|get_servers");
},
async startServer(model: SupportedSttModel | null) : Promise<string> {
    return await TAURI_INVOKE("plugin:local-stt|start_server", { model });
},
async stopServer(serverType: ServerType | null) : Promise<boolean> {
    return await TAURI_INVOKE("plugin:local-stt|stop_server", { serverType });
},
async listSupportedModels() : Promise<SttModelInfo[]> {
    return await TAURI_INVOKE("plugin:local-stt|list_supported_models");
},
async listSupportedLanguages(model: SupportedSttModel) : Promise<Language[]> {
    return await TAURI_INVOKE("plugin:local-stt|list_supported_languages", { model });
},
async getCustomBaseUrl() : Promise<string> {
    return await TAURI_INVOKE("plugin:local-stt|get_custom_base_url");
},
async getCustomApiKey() : Promise<string | null> {
    return await TAURI_INVOKE("plugin:local-stt|get_custom_api_key");
},
async setCustomBaseUrl(baseUrl: string) : Promise<null> {
    return await TAURI_INVOKE("plugin:local-stt|set_custom_base_url", { baseUrl });
},
async setCustomApiKey(apiKey: string) : Promise<null> {
    return await TAURI_INVOKE("plugin:local-stt|set_custom_api_key", { apiKey });
},
async getProvider() : Promise<Provider> {
    return await TAURI_INVOKE("plugin:local-stt|get_provider");
},
async setProvider(provider: Provider) : Promise<null> {
    return await TAURI_INVOKE("plugin:local-stt|set_provider", { provider });
},
async getCustomModel() : Promise<SupportedSttModel | null> {
    return await TAURI_INVOKE("plugin:local-stt|get_custom_model");
},
async setCustomModel(model: SupportedSttModel) : Promise<null> {
    return await TAURI_INVOKE("plugin:local-stt|set_custom_model", { model });
},
async transcribeAudioFile(filePath: string) : Promise<Word2[]> {
    return await TAURI_INVOKE("plugin:local-stt|transcribe_audio_file", { filePath });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AmModel = "am-parakeet-v2" | "am-parakeet-v3" | "am-whisper-large-v3"
export type GgmlBackend = { kind: string; name: string; description: string; total_memory_mb: number; free_memory_mb: number }
export type Language = { iso639: string }
export type Provider = "Local" | "Custom"
export type ServerHealth = "unreachable" | "loading" | "ready"
export type ServerType = "internal" | "external" | "custom"
export type SpeakerIdentity = { type: "unassigned"; value: { index: number } } | { type: "assigned"; value: { id: string; label: string } }
export type SttModelInfo = { key: SupportedSttModel; display_name: string; size_bytes: number }
export type SupportedSttModel = WhisperModel | AmModel | string
export type TAURI_CHANNEL<TSend> = null
export type WhisperModel = "QuantizedTiny" | "QuantizedTinyEn" | "QuantizedBase" | "QuantizedBaseEn" | "QuantizedSmall" | "QuantizedSmallEn" | "QuantizedLargeTurbo"
export type Word2 = { text: string; speaker: SpeakerIdentity | null; confidence: number | null; start_ms: number | null; end_ms: number | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
